### ISSUE TITLE
savefig() missing 1 required positional argument: 'fname'

### ISSUE THREAD

**Issue by snabb** [scylladb/diskplorer#5]
I did not get a graph. I got this error instead:
```
foo@snail:/mnt$ python3 ~/src/diskplorer/diskplorer.py 
Traceback (most recent call last):
  File "/home/snabb/src/diskplorer/diskplorer.py", line 159, in <module>
    plt.savefig(filename=output_filename)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 701, in savefig
    res = fig.savefig(*args, **kwargs)
TypeError: savefig() missing 1 required positional argument: 'fname'
foo@snail:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
foo@snail:~$ dpkg -l python3-matplotlib
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version         Architecture    Description
+++-=====================-===============-===============-===============================================
ii  python3-matplotlib    2.1.1-2ubuntu3  amd64           Python based plotting system in a style similar

```

**Comment by asias** [comment]
@avikivity  

I saw the same on fedora 28 with pthon3-matplotlib-2.2.3-1.fc28.x86_64


```
 $ ./diskplorer.py -s 5g
Traceback (most recent call last):
  File "./diskplorer.py", line 159, in <module>
    plt.savefig(filename=output_filename)
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 695, in savefig
    res = fig.savefig(*args, **kwargs)
TypeError: savefig() takes exactly 2 arguments (1 given)
```

**Comment by sh4dowm4ster** [comment]
Yes, there is an error on the line 162. 
Should be: 
plt.savefig(**fname**=output_filename)

**Comment by avikivity** [comment]
thanks.
